apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: argocd
spec:
  type: NodePort
  ports:
    - port: 3100
      targetPort: 3100
      nodePort: 31000
      protocol: TCP
      name: http
  selector:
    app: loki
