loki:
  service:
    type: ClusterIP
    port: 3100

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  persistence:
    enabled: true
    size: 20Gi
    storageClass: standard
  
  replicaCount: 0 # <-- ПЕРЕНЕСЕНО СЮДА, ВНУТРЬ СЕКЦИИ LOKI
  # Если чарт Loki имеет отдельные компоненты (например, 'loki-gateway', 'loki-read', 'loki-write'),
  # возможно, для них тоже нужно установить replicaCount: 0 или enabled: false.
  # Проверьте values.yaml самого чарта Loki.


promtail:
  enabled: false # <-- Изменено на false для отключения Promtail
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 412Mi

# replicaCount: 1 # <-- ЭТУ СТРОКУ УДАЛИТЕ ОТСЮДА

grafana:
  enabled: false # Правильно, Grafana отключена

fullnameOverride: "loki-stack"