loki:
  service:
    type: NodePort
    port: 3100
    nodePort: 30099 # Выберите доступный NodePort (30000-32767)

  # Правильное расположение секции resources
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

  persistence:
    enabled: true
    size: 20Gi
    storageClass: standard
  
  # replicaCount должен находиться внутри секции 'loki:'
  replicaCount: 1 

promtail:
  enabled: false # Отключаем Promtail
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 412Mi

grafana:
  enabled: false # Grafana отключена

fullnameOverride: "loki-stack"