apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-wal-pvc
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # поменяй, если у тебя другой класс хранения
