# Описание объекта Deployment, который управляет созданием и обновлением наборов Pod'ов
apiVersion: apps/v1       # Версия API Kubernetes для Deployment
kind: Deployment          # Тип объекта — Deployment

metadata:
  name: current-time      # Имя этого Deployment — уникальный идентификатор в namespace

spec:
  replicas: 1             # Сколько копий (подов) запустить одновременно — 3

  selector:
    matchLabels:
      app: current-time   # Как выбрать поды, которые контролирует этот Deployment (метка app=current-time)

  template:               # Шаблон для создаваемых подов
    metadata:
      labels:
        app: current-time # Метка, которая будет присвоена создаваемым подам — нужна для связывания с селектором и сервисом

    spec:                 # Описание пода и его контейнеров
      containers:
      - name: current-time
        image: neorld/current-time:latest
        imagePullPolicy: IfNotPresent # <--- Добавьте или убедитесь, что это Always
        command: [ "python" ]
        args: [ "current_time.py" ]
        volumeMounts:
        - name: varlog
          mountPath: /var/log/current-time
          #mountPropagation: HostToContainer

      volumes:                     
      - name: varlog
        emptyDir: {}
      - name: varlogpods
        hostPath:
          path: /var/log/pods
          type: Directory
      - name: rootfs
        hostPath:
          path: /
          type: Directory
---

# Описание сервиса Kubernetes, который открывает доступ к подам снаружи кластера
apiVersion: v1               # Версия API Kubernetes для Service
kind: Service                # Тип объекта — Service (служба)

metadata:
  name: current-time-service # Имя сервиса, по которому мы будем обращаться к приложению
spec:
  type: NodePort             # Тип сервиса — NodePort позволяет обращаться к сервису через IP любой ноды кластера и фиксированный порт
  selector:
    app: current-time        # Связывает сервис с подами, у которых есть метка app=current-time (тот же, что в Deployment)
  ports:
    - protocol: TCP          # Протокол связи (TCP)
      port: 1001            # Порт, на котором сервис слушает внутри кластера (для других сервисов и подов)
      targetPort: 1001      # Порт на контейнерах, на который перенаправляется трафик (тот же, что containerPort)
      nodePort: 31001       # Внешний порт на нодах, через который можно достучаться к сервису извне (открытый порт)