apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector-mon
  namespace: argocd
spec:
  project: mon

  sources: 

--
  - repoURL: https://helm.vector.dev 
    chart: vector                 # Имя чарта в этом репозитории
    targetRevision: 0.20.0        # <--- ВЕРСИЯ ЧАРТА Vector, которую вы хотите использовать

 --
  - repoURL: 'https://github.com/nematullo/helm-test-learning.git' # URL ВАШЕГО GIT-РЕПОЗИТОРИЯ
    targetRevision: HEAD         
    path: vector      

    
  helm: 
    valueFiles:
      - $argocd_app_source_1/neo-values.yaml 

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true