apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: argocd-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Порт HTTP на поде
      nodePort: 30080 # Назначенный NodePort для HTTP
      name: http
    - protocol: TCP
      port: 443
      targetPort: 8081 # Порт HTTPS на поде
      nodePort: 30443 # Назначенный NodePort для HTTPS
      name: https