createConfigmap: true

adminUser: admin
adminPassword: mysecurepassword

grafana.ini:
  server:
    domain: ''
    root_url: http://localhost:30125
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net

grafana:
  service:
    enabled: true
    type: NodePort
    port: 80
    targetPort: 3000
    nodePort: 30125
  persistence:
    enabled: false
  server:
    root_url: http://localhost:30125
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  env:
    GF_DATABASE_TYPE: postgres
    GF_DATABASE_HOST: postgresql-grafana.argocd.svc.cluster.local:5432
    GF_DATABASE_NAME: grafana
    GF_DATABASE_USER: grafana
    GF_DATABASE_PASSWORD: grafana1234
    GF_DATABASE_SSL_MODE: disable
    GF_DATABASE_MAX_OPEN_CONN: "100"
    GF_DATABASE_MAX_IDLE_CONN: "100"
    GF_DATABASE_CONN_MAX_LIFETIME: "14400"
    GF_DATABASE_LOG_QUERIES: "true"

#persistence:
#  type: pvc
#  enabled: true.
#  volumeName: ""
#  accessModes:
#    - ReadWriteOnce
#  size: 1Gi

#  type:  statefulset

#  # Собственный volume с hostPath
#  volumes:
#    - name: grafana-storage
#      hostPath:
#        path: /home/neo/grafana-data
#        type: DirectoryOrCreate

#  mounts:
#    - name: grafana-storage
#      mountPath: /var/lib/grafana