apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: mon

  source:
    repoURL: 'https://github.com/nematullo/helm-test-learning.git'
    targetRevision: HEAD
    path: loki
    #helm:
    #  valueFiles:
    #    - neo-values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd

  syncPolicy:
    automated:
      prune: true       # Удаляет ресурсы, которых больше нет в Git
      selfHeal: true    # Восстанавливает удалённые или изменённые вручную ресурсы
    syncOptions:
    - CreateNamespace=true
