apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/nematullo/helm-test-learning.git'
    targetRevision: HEAD
    path: rabbitmq
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: false       # Удаляет ресурсы, которых больше нет в Git
      selfHeal: true    # Восстанавливает удалённые или изменённые вручную ресурсы
    syncOptions:
    - CreateNamespace=true
