# /home/neo/Документы/helm-test-learning/argocd-app-kube/argocd-admin-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd # Убедитесь, что это ваш целевой неймспейс
type: Opaque
stringData: # Используйте 'stringData' для передачи значений в виде обычного текста. Kubernetes сам закодирует их в base64.
  admin.password: "$2a$10$8kQw3poG1LPTAR9/EqYsnuslwhCOKkS3vcucSyKaNno0pLUzkcwkK" # Ваш захэшированный пароль
  admin.passwordMtime: "2025-06-09T11:48:17Z" # ВАЖНО: Укажите текущее UTC время (или более позднее, чем сейчас), чтобы Argo CD обновил пароль. Я поставил текущую дату и время.