# kubernetes-vector-agent/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-agent # Имя ServiceAccount
  namespace: argocd   # Неймспейс, где будет развернут Vector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # <-- Кластерная роль
metadata:
  name: vector-agent # Имя ClusterRole
rules:
  - apiGroups: [""]
    resources:
      - "nodes"
      - "nodes/proxy"
      - "pods"
      - "namespaces"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["extensions"] # Для DaemonSets в старых версиях
    resources: ["daemonsets"]
    verbs: ["get"]
  - apiGroups: ["apps"]       # Для DaemonSets в новых версиях
    resources: ["daemonsets"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding # <-- Кластерная привязка
metadata:
  name: vector-agent # Имя ClusterRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector-agent # Ссылка на ClusterRole выше
subjects:
  - kind: ServiceAccount
    name: vector-agent # Ссылка на ServiceAccount выше
    namespace: argocd   # Неймспейс ServiceAccount 

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mon
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
