apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-agent
  namespace: argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role # <-- Заменили ClusterRole на Role
metadata:
  name: vector-agent-role # Изменили имя для ясности
  namespace: argocd      # Указали пространство имен
rules:
  - apiGroups: [""]
    resources:
      - "nodes"
      - "nodes/proxy"
      - "pods"
      - "namespaces"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["extensions"]
    resources: ["daemonsets"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding # <-- Заменили ClusterRoleBinding на RoleBinding
metadata:
  name: vector-agent-rolebinding # Изменили имя для ясности
  namespace: argocd           # Указали пространство имен
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role # <-- Ссылка на Role, а не ClusterRole
  name: vector-agent-role # Ссылка на Role выше
subjects:
  - kind: ServiceAccount
    name: vector-agent
    namespace: argocd