configs:
  secret:
    createSecret: true
    argocdServerAdminPassword: "$2a$10$8kQw3poG1LPTAR9/EqYsnuslwhCOKkS3vcucSyKaNno0pLUzkcwkK"
    argocdServerAdminPasswordMtime: "2025-05-26T00:00:00Z"
    clearPassword: "11221122"   # вот этот ключ нужно добавить

  cm:
    admin.enabled: true

  params:
    server.insecure: true

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, admin, role:admin



server:
  service:
    type: NodePort
    ports:
      http: 8080
      https: 8443
    nodePorts:
      http: 30080
      https: 30443

repoServer:
  service:
    type: NodePort
    port: 8081
    nodePort: 30081

dex:
  enabled: true
  service:
    type: NodePort
    ports:
      http: 5556
      grpc: 5557
    nodePorts:
      http: 30556
      grpc: 30557

redis:
  auth:
    existingSecret: argocd-redis


redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: "11221122"
  master:
    service:
      type: NodePort
      port: 6379
      nodePort: 30639
