# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

fullnameOverride: "my-redis-neo"
## @param namespaceOverride Строка для полного переопределения common.names.namespace
##
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"
master:
  service:
    type: NodePort
    port: 6379
    targetPort: 6379
    nodePort: 30091
replica:
  service:
    type: NodePort
    port: 6379
    nodePort: 30090
sentinel:
  enabled: false